### ISSUE TITLE
Installing from Source

### ISSUE THREAD

**Issue by bkoffler** [aws/aws-php-sns-message-validator#10]
Hi -

Thanks for this validator. My endpoints have been operating manually without the SDK for some time and i really want to get a validator back online. I am getting constant errors when i try to install this through composer, and i am looking for some guidance on where to install it if i am going to install it from the source. 

Please let me know if this makes sense when you have a chance.

**Comment by jeremeamia** [comment]
Could you provide information about the errors? Maybe we can help resolve those.

**Comment by bkoffler** [comment]
The only error was sending that message without trying all the tricks up my sleeve :). I think i have it all working currently, but will do some more testing to make sure later in the week. If i find a problem that i can't figure out i will shoot you a message but now that i am seeing how it has to work your examples should be all i need to move forward.

**Comment by jeskew** [comment]
Sounds from your last message like no news is good news.

Closing on the assumption that everything installed correctly; please feel free to reopen if you have any further questions.
