### ISSUE TITLE
Question: Guaranteed no naming clashes with aws/aws-sdk-php?

### ISSUE THREAD

**Issue by siwinski** [aws/aws-php-sns-message-validator#12]
Are the classes in this package guaranteed to not clash with [aws/aws-sdk-php](https://github.com/aws/aws-sdk-php) both 2.x and 3.x?

**Comment by jeremeamia** [comment]
This package is meant for use with 3.x, and will not clash with it.

Version 2.x has it's own SNS validator code, from which this was originally extracted, therefore, there are conflicts with 2.x.

**Comment by jeskew** [comment]
@jeremeamia What conflicts do you see? There is significant overlap between the functionality of the classes in this package and some classes in version 2.x's, but they are in different namespaces (`Aws\Sns\MessageValidator` for 2.x vs `Aws\Sns` for this package).

I can't see a good reason to use this package with v2 of the AWS SDK for PHP, but it won't cause any conflicts. This package will continue to use the `Aws\Sns` namespace and the legacy version of the SDK will continue to use `Aws\Sns\MessageValidator`, so you can count on the two not conflicting.

**Comment by jeremeamia** [comment]
Oh yeah, you're right. It shouldn't conflict. That's cool. I'm guessing @siwinski has a hard requirement on this library and a softer 2.x|3.x requirement on the SDK (or he wants to support either, at least)

**Comment by jeskew** [comment]
Makes sense. I have an open PR on Bernard to make a similar change.

**Comment by siwinski** [comment]
FYI: My use case is that downstream (Fedora/EPEL) I package both SDK versions 2.x (as `/usr/share/php/Aws`) and 3.x (as `/usr/share/php/Aws3`) and allow dual-install because not many packages have updated to 3.x yet.  I was going to downstream package this library under `/usr/share/php/Aws` if there were no naming conflicts.

**Comment by remicollet** [comment]
To be clear, the "possible" conflict is for **Aws\Sns\Exception **namespace which is used in both.

**Comment by jeskew** [comment]
For message-related exceptions, this package uses `Aws\Sns\Exception\InvalidSnsMessageException`, whereas v2 of the SDK uses several exceptions in the `Aws\Sns\MessageValidator\Exception` namespace.
