### ISSUE TITLE
Allow Aws\Sns\Message

### ISSUE THREAD

**Issue by ckrack** [aws/aws-php-sns-message-validator#13]
Allow usage of ``Aws\Sns\Message``instead of limiting to ``Aws\Sns\MessageValidator\Message``.
This should be essentially the same.

Can be fixed by moving the typecheck into the method.
Do you want me to send a pull-request?

**Comment by jeskew** [comment]
Are you referring to the `Message` typehints on the methods of the `Aws\Sns\MessageValidator` class? `Aws\Sns\MessageValidator\Message` is not imported into that file, so `Message` there refers to `Aws\Sns\Message`.

**Comment by ckrack** [comment]
Weird, seems like i missed this when changing things. 
I originally had:
``use Aws\Sns\MessageValidator\MessageValidator`` (which is wrong of course)
``use Aws\Sns\Message``

Which lead to this error: ``Argument 1 passed to Aws\\Sns\\MessageValidator\\MessageValidator::isValid() must be an instance of Aws\\Sns\\MessageValidator\\Message, instance of Aws\\Sns\\Message given``

Do you know if this is documented behaviour in PHP 5.6?
Otherwise I might want to report this to the PHP bugtracker, as ``use ..MessageValidator\\MessageValidator`` should fail.

**Comment by jeskew** [comment]
It sounds like you're using this package and v2 of the AWS SDK for PHP. With v2, make sure you either use the validator in the `Aws\Sns\MessageValidator` namespace (which is bundled with the SDK) or the validator in the `Aws\Sns` namespace (which this package provides). Mixing and matching classes from the two is not recommended.

**Comment by ckrack** [comment]
Well spotted, nice crystal ball you must have there!

Indeed the project was using v2.8 of aws-sdk-php.
Using v3 now and the behaviour is correct as expected.

Thank you.

**Comment by jeskew** [comment]
Glad to hear everything worked out! Just for future reference, though, this package *is* compatible with v2.8 of the AWS SDK for PHP. You would just need to use the `Aws\Sns\Message` class with the `Aws\Sns\MessageValidator` class and/or use the `Aws\Sns\MessageValidator\Message` class with the `Aws\Sns\MessageValidator\MessageValidator` class.
