### ISSUE TITLE
Split project is confusing to find

### ISSUE THREAD

**Issue by deviantintegral** [aws/aws-php-sns-message-validator#15]
The [official SDK docs](http://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Sns.MessageValidator.html) don't make any mention that these classes are in a separate package. It's especially confusing with the exception classes being in the core SDK, and most other services being in the core SDK as well. Perhaps this isn't just a docs update, but should be a dependency of the core SDK? If the point of the split package is to not force the SDK and Guzzle onto clients, then making this a dependency of the SDK doesn't seem like a big deal.

**Comment by cjyclaire** [comment]
@deviantintegral Thanks for the feedback, this package is intended for SDK V3, SDK V2 includes SNS message validation at core package. Thus, it's addressed in SDK guide at [migration part](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/migration.html#many-higher-level-abstractions-have-changed).

Your feedback is valuable to us, I'll add more documentation in SDK guide about those split projects information.

**Comment by cjyclaire** [comment]
Closing, tracking with PR opened, yet feel free to reopen with further comments or questions.
