### ISSUE TITLE
failed to open stream

### ISSUE THREAD

**Issue by Zelfapp** [aws/aws-php-sns-message-validator#18]
This is an issue with my host setup, but hoping someone can steer me in the right direction. I'm seeing the following warnings in my logs. Lots of chatter about missing ca certificates possibly? I'm running centos CentOS Linux release 7.3 and AWS php sdk 3.29.7.

Somehow the SNS still appears to be processed, but how do I fix my setup here?

- file_get_contents(): SSL: Connection reset by peer
- file_get_contents(): Failed to enable crypto
- file_get_contents(https://sns.us-west-2.amazonaws.com/SimpleNotificationService): failed to open stream: operation failed /vendor/aws/aws-php-sns-message-validator/src/MessageValidator.php

**Comment by jeskew** [comment]
Hi @Zelfapp,

This library isn't doing anything special with regards to SSL; it's just relying on PHP's `file_get_contents` function to properly handle accessing paths using the `https` protocol. Do you see any warnings or errors if you execute `file_get_contents('https://www.google.com')`?

**Comment by joshbernfeld** [comment]
You must have openssl enabled and if that still doesn't work check here:
https://stackoverflow.com/questions/1975461/how-to-get-file-get-contents-to-work-with-https
