### ISSUE TITLE
Push Notification implementation

### ISSUE THREAD

**Issue by sumit784** [aws/aws-php-sns-message-validator#24]
I am looking for a sample code or project , which uses AWS PHP sdk to send "In app notification" on ios and android using SNS

I got lots of examples for simple text messages sending and subscription confirmation etc, but haven't come across anything that details out the "Push notifications on mobile devices" 

Is there anything ?

**Comment by kstich** [comment]
Try using this guide for [SNS based mobile push notifications](http://docs.aws.amazon.com/sns/latest/dg/SNSMobilePush.html).
