### ISSUE TITLE
InvalidArgumentException: "Message" is required to verify the SNS Message.

### ISSUE THREAD

**Issue by thanush** [aws/aws-php-sns-message-validator#29]
i'm using laravel for getting sns messages everything is fine but when i'm getting post request it's throwing error like **"InvalidArgumentException: "Message" is required to verify the SNS Message."** i followed the document exactly. please tell me did i miss anything?

**Comment by kstich** [comment]
This means that the data passed in to create a `Message` object did not include the `'Message'` field.

**Comment by thanush** [comment]
actually i delete topic and create new one working fine now.. i don't know previously why isn't work. anyway thanks for the reply @kstich

**Comment by i-ira** [comment]
This issue has plagued me as well, in particular when sending SNS Notifications via Elastic Transcoder. Elastic Transcoder Notification payloads don't seem to contain a "Message" field.

**Comment by hamid09430** [comment]
Same Error here.

Elemental Media Converter does not have message field.
i am receiving my data in email protocol but not in https protocol of SNS 

Anyone knows what's the issue is
