### ISSUE TITLE
SNS message type header not provided in request header

### ISSUE THREAD

**Issue by kamerk22** [aws/aws-php-sns-message-validator#36]
As per the `fromRawPostData()` function, it required `HTTP_X_AMZ_SNS_MESSAGE_TYPE'` but AWS is sending `X-Amz-Sns-Message-Type` in the header.

```
public static function fromRawPostData()
{
       // Make sure the SNS-provided header exists.
       if (!isset($_SERVER['HTTP_X_AMZ_SNS_MESSAGE_TYPE'])) {
       throw new \RuntimeException('SNS message type header not provided.');
}
```

as per Documentation [SNS DOC](https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.html) current header is `X-Amz-Sns-Message-Type`.
Thank You.

**Comment by kstich** [comment]
This is the correct transformation PHP does when shifting the request in to the `$_SERVER` variable.
