### ISSUE TITLE
Support for psr/http-message 2.0

### ISSUE THREAD

**Issue by ionutantohi** [aws/aws-php-sns-message-validator#62]
### Describe the bug

This package can't not be installed on existing projects which require psr/http-message 2.0

### Expected Behavior

Package to be installed within projects which depend on psr/http-message 2.0

### Current Behavior

`composer require aws/aws-php-sns-message-validator` failes with below error

aws/aws-php-sns-message-validator[1.5.0, ..., 1.8.0] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match.

### Reproduction Steps

Install the package along with psr/http-message 2.0 as root requirement

### Possible Solution

Update the dependency or maybe remove it? See below PR

https://github.com/aws/aws-php-sns-message-validator/pull/56

### SDK version used

n/a

### Environment details (OS name and version, etc.)

n/a

**Comment by yenfryherrerafeliz** [comment]
Hi @ionutantohi, please see the following announcement [here](https://github.com/aws/aws-php-sns-message-validator/discussions/67), where we will be deprecating PHP versions 7.2.5 and prior, on this repo. We have the following [PR](https://github.com/aws/aws-php-sns-message-validator/pull/66), which includes psr/http-message 2.0, ready to be merged after the target deprecation date.

Thanks!

**Comment by yenfryherrerafeliz** [comment]
PR has been merged!.
